Penambahan fitur bagi pengguna terdaftar
laymonage/kbbi-python pull request #12
Opened 2020-03-17 16:19 UTC by noaione

Relevan: #8 

### Contoh
`KBBI('roh', email="REDACTED", password="REDACTED")`
```py
roh
bentuk tidak baku: ruh
Etimologi: [Arab] <n> <sg> <f/m> » رُوْحٌ (rūh): tiupan; sesuatu yang membuat manusia dapat hidup
1. (n)  sesuatu (unsur) yang ada dalam jasad yang diciptakan Tuhan sebagai penyebab adanya hidup (kehidupan); nyawa: jika -- sudah berpisah dari badan, berakhirlah kehidupan seseorang
2. (n)  makhluk hidup yang tidak berjasad, tetapi berpikiran dan berperasaan (malaikat, jin, setan, dan sebagainya)
3. (n) (ki)  semangat; spirit: kedamaian bagi seluruh warga sesuai dengan -- Islam
Gabungan Kata: roh Kudus; roh suci
```

`KBBI('coba', email="REDACTED", password="REDACTED")`
```py
co.ba
1. (v)  silakan; sudilah; tolong (untuk menghaluskan suruhan atau ajakan): -- lihat kalau-kalau ia ada di rumah
2. (p)  kata afektif untuk menyatakan perasaan jengkel dan sebagainya: --, orang apa ini, begitu saja tidak bisa
3. (p)  seandainya; jika: -- tidak kutolong, celaka engkau
Kata Turunan: coba-coba; cobaan; mencoba; mencoba-coba; mencobai; mencobakan; pencoba; pencobaan; percobaan
Gabungan Kata: coba dan ralat
Peribahasa (mengandung [co.ba]): coba-coba menanam mumbang, kalau tumbuh sunting negeri, dicoba-coba bertanam mumbang, moga-moga tumbuh kelapa
```

Mungkin nanti bisa diganti beberapa variabelnya

2020-03-17 17:21 UTC, laymonage commented
Wah, padahal saya baru saja mau rilis versi 0.4.0 :sweat_smile:. Terima kasih! Saya coba tinjau dulu, ya.

2020-03-17 17:45 UTC, laymonage requested changes
Kerja bagus, keren sekali! Saya belum sempat mencobanya sih, tetapi melihat kodenya sekilas, sepertinya sudah cukup baik. Ini hasil tinjauan pertama saya.

2020-03-17 17:45 UTC, laymonage commented on kbbi/kbbi.py
> +    def __init__(self, kueri, email=None, password=None):
Kalau seperti ini, sayangnya proses autentikasi akan dilakukan setiap kali ingin mengambil laman KBBI.

Saya rasa urusan autentikasi sebaiknya dilakukan dengan objek dari *class* terpisah. Mungkin kita bisa membuat *class* `AutentikasiKBBI` yang menangani urusan autentikasi (pindahkan metode `_autentikasi()` ke sana). Lalu, kelas `KBBI` akan menerima objek `AutentikasiKBBI` tersebut (yang di dalamnya terdapat `Session`). Dengan begitu, pengguna cukup buat objek `AutentikasiKBBI` **satu kali** (sehingga `_autentikasi()` hanya dipanggil satu kali), dan menggunakan objek tersebut untuk pembuatan objek-objek `KBBI` berikutnya.

2020-03-17 17:45 UTC, laymonage commented on kbbi/kbbi.py
> +    def _autentikasi(self, email, password):
Secara umum, metode ini sudah oke. Sebenarnya bisa pakai `BeautifulSoup` supaya tidak perlu keajaiban regex, tetapi berhubung kita tidak perlu mengolah HTML halaman login, begini saja lebih baik.

2020-03-17 17:45 UTC, laymonage commented on kbbi/kbbi.py
> +        for le in lain_lain:
Saya melihat pola untuk ketiga hal ini... mungkin bisa disederhanakan? :wink:

2020-03-17 17:45 UTC, laymonage commented on kbbi/kbbi.py
> +        help="gunakan indentasi sebanyak N untuk serialisasi JSON",
Ups, pesan `help`-nya belum diganti :smile:

2020-03-17 17:45 UTC, laymonage commented on kbbi/kbbi.py
>      except (TidakDitemukan, TerjadiKesalahan, BatasSehari) as e:
`GagalAutentikasi` juga akan perlu dimasukkan ke dalam sini. Mungkin ini saatnya kita buat abstraksi untuk galat yang kita buat, misal `class Galat(Exception)` kemudian semua *class* galat yang dibuat akan diturunkan dari `Galat`.

2020-03-17 17:48 UTC, laymonage commented on kbbi/kbbi.py
> +    def __init__(self, kueri, email=None, password=None):
Oh ya, kalau hanya begini sayangnya pemanggilan via CLI tetap harus melakukan autentikasi berkali-kali. Mungkin kita bisa tambahkan opsi autentikasi dengan `.AspNet.ApplicationCookie` agar pemanggilan via CLI tidak harus *login* terus menerus.

2020-03-17 23:26 UTC, noaione commented on kbbi/kbbi.py
> +    def __init__(self, kueri, email=None, password=None):
Iya, untuk sementara harus call `_autentikasi()` tiap summon class `KBBI`.
Mungkin bisa coba implemen local save untuk cookies di `localappdata` atau semacamnya untuk yang CLI.

2020-03-18 08:15 UTC, laymonage requested changes
Terima kasih sudah merevisi PR ini. Berikut hasil tinjauan kedua saya.

2020-03-18 08:15 UTC, laymonage commented on kbbi/kbbi.py
> +        save_folder = os.path.join(
Ketimbang pakai `os.path`, mungkin lebih baik pakai `pathlib`. Direktori `home` bisa didapat dengan [`pathlib.Path.home`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.home).

2020-03-18 08:15 UTC, laymonage commented on kbbi/kbbi.py
> +        for le in lain_lain:
```suggestion

terkait = {
    "Kata Turunan": self.kata_turunan,
    "Gabungan Kata": self.gabungan_kata,
    "Peribahasa": self.peribahasa,
    "Kiasan": self.kiasan,
}

for le in lain_lain:
    if not le:
        continue
    le_txt = le.text.strip()
    for jenis, daftar in terkait.items():
        if jenis in le_txt:
            kumpulan = le.next_sibling
            if kumpulan:
                 kumpulan = kumpulan.find_all("a")
                 daftar.extend([k.text for k in kumpulan if k])
```

2020-03-18 08:15 UTC, laymonage commented on kbbi/kbbi.py
> +                self.sesi.headers.update({"Cookie": fp.read()})
Sepertinya cara yang baik untuk mengatur *cookie* pada objek `Session` adalah dengan memanfaatkan objek `RequestsCookieJar` (dapat diakses dengan `self.sesi.cookies`) dan menggunakan *method* [`set`](https://2.python-requests.org/en/v2.8.1/api/#requests.cookies.RequestsCookieJar.set) (atau `update`/semacamnya). 

Ketimbang `.txt` dengan format `key=value`, mungkin lebih baik pakai JSON dan memanfaatkan *method* [`dict_from_cookiejar`](https://2.python-requests.org/en/v2.8.1/api/#requests.utils.dict_from_cookiejar) serta `cookiejar_from_dict`. Kemudian, `dict` dimuat/disimpan dengan [`json.load`](https://docs.python.org/3/library/json.html#json.load) dan `json.dump`. Silakan saja ingin menyimpan seluruh *cookie* atau `.AspNet.ApplicationCookie` saja.

Kalau dirasa terlalu merepotkan, saya bisa bantu melanjutkan.

2020-03-18 08:15 UTC, laymonage commented on kbbi/kbbi.py
> +        TidakDitemukan,
Buat *class* berikut:

```python
class Galat(Exception):
    pass
```

Kemudian buat agar `TidakDitemukan`, `TerjadiKesalahan`, `BatasSehari`, dan `GagalAutentikasi` menjadi *subclass* dari `Galat`. Lalu, di sini cukup:

```python
except Galat as e:
    print(e)
```

2020-03-18 08:15 UTC, laymonage commented on kbbi/kbbi.py
> +        if aspcookie:
Saya penasaran, kalau *cookie*-nya sudah kedaluwarsa, apa yang akan terjadi? :thinking:

2020-03-18 08:18 UTC, laymonage commented on kbbi/kbbi.py
> +        if aspcookie:
Oh ya, saya lupa tambahkan. Mungkin akan lebih baik juga kalau ada opsi CLI untuk menghapus/mengabaikan *cookie* yang sudah disimpan.

2020-03-18 08:50 UTC, noaione commented on kbbi/kbbi.py
> +                self.sesi.headers.update({"Cookie": fp.read()})
Mungkin bisa dilanjutkan, saya ubah dulu `os.path` ke [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) dulu aja

2020-03-19 11:52 UTC, laymonage commented on kbbi/kbbi.py
> +                self.sesi.headers.update({"Cookie": fp.read()})
Baik, saya lanjutkan ya.

2020-03-21 07:23 UTC, laymonage approved these changes

2020-03-22 00:43 UTC, merged