saran entri lain yang mirip #13
laymonage/kbbi-python pull request #15
Opened 2020-04-08 04:36 UTC by maulana20

hallo mas @laymonage .. saya PR dengan menambahkan class Saran untuk menampilkan data saran "entri lain yang mirip". Pengecekannya pada _cek_galat apabila muncul "Berikut beberapa saran entri lain yang mirip." _init_entri di alihkan ke class Saran

```js
auth = AutentikasiKBBI("<email>", <password>")
kata = KBBI("huk", auth)
print(kata)
```
![image](https://user-images.githubusercontent.com/11070656/78744739-8c08f100-798c-11ea-8b87-ea3b8f23935d.png)

```js
print(json.dumps(kata.serialisasi(), indent=2))
```
![image](https://user-images.githubusercontent.com/11070656/78744912-f9b51d00-798c-11ea-8cf6-a8967af99f36.png)

2020-04-11 16:57 UTC, laymonage commented on src/kbbi/kbbi.py
> +            "kata_lainnya": []
Saya rasa kita tidak perlu membungkus daftar saran dalam `dict` lagi, langsung saja dalam `list`.

2020-04-12 02:47 UTC, laymonage requested changes
Halo @maulana20, terima kasih atas kontribusinya!

Berhubung ini mengandung perubahan yang tidak kompatibel dengan versi sebelumnya, sepertinya saya akan targetkan ini untuk versi 0.5.0 saja (bukan 0.4.x).

Selain itu, boleh tolong di-*rebase* dulu? Saya baru saja merilis versi 0.4.1 untuk menyesuaikan dengan KBBI V Daring versi 3.0.0.

Oh ya, mungkin info mengenai fitur ini bisa ditambahkan ke `README.md`. Jika memungkinkan, tolong tambahkan juga tesnya agar *coverage* tetap 100%.

Terima kasih!

2020-04-12 02:47 UTC, laymonage commented on src/kbbi/kbbi.py
> +            "kata_lainnya": "\nKata Lainnya",
Saya rasa ini tidak perlu, laman KBBI tidak menuliskan `"Kata Lainnya"`. Selain itu, saran entri belum tentu berupa kata, bisa saja huruf, singkatan, atau frasa.

2020-04-12 02:47 UTC, laymonage commented on src/kbbi/kbbi.py
> +        self.info = 'Berikut beberapa saran entri lain yang mirip.'
Sepertinya ini tidak perlu.

2020-04-12 02:47 UTC, laymonage commented on src/kbbi/kbbi.py
> +        hasil += self._saran_entri()
Langsung saja

```python
hasil = "Berikut beberapa saran entri lain yang mirip."
hasil += self._saran_entri()
```

2020-04-12 05:28 UTC, maulana20 commented
baik mas @laymonage .. nanti akan saya PR kembali dengan perbaikan dan tambahan test nya ..

2020-04-12 05:48 UTC, laymonage commented
> baik mas @laymonage .. nanti akan saya PR kembali dengan perbaikan dan tambahan test nya ..

Sebenarnya tidak perlu buat PR baru, PR yang ini bisa di-*rebase* berdasarkan `master` yang sekarang. Namun, kalau kesulitan melakukan *rebase*, silakan membuat PR baru :)

2020-04-12 06:09 UTC, maulana20 commented
@laymonage biasanya saya pake pull merge push .. tpi gpp mas saya coba rebase :)

2020-04-13 06:48 UTC, closed without merging